version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./frontend/fusen/build:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - react
  react:
    container_name: fusen_react
    build: ./frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    tty: true
    
  go:
    container_name: fusen_god
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "1323:1323"
    environment:
      - GO_ENV=development
      - HOST=0.0.0.0

      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - ROOT_URL=${ROOT_URL}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - JWT_KEY=${JWT_KEY}

    depends_on:
      - postgres
    tty: true

  postgres:
    container_name: fusen_db
    image: postgres:15.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data:
