// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("BoardToUserUsingUser", testBoardToOneUserUsingUser)
	t.Run("CheckpointToFusenUsingFusen", testCheckpointToOneFusenUsingFusen)
	t.Run("FusenToUserUsingUser", testFusenToOneUserUsingUser)
	t.Run("PreferenceToUserUsingUser", testPreferenceToOneUserUsingUser)
	t.Run("TagToUserUsingUser", testTagToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("FusenToCheckpoints", testFusenToManyCheckpoints)
	t.Run("UserToBoards", testUserToManyBoards)
	t.Run("UserToFusens", testUserToManyFusens)
	t.Run("UserToPreferences", testUserToManyPreferences)
	t.Run("UserToTags", testUserToManyTags)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("BoardToUserUsingBoards", testBoardToOneSetOpUserUsingUser)
	t.Run("CheckpointToFusenUsingCheckpoints", testCheckpointToOneSetOpFusenUsingFusen)
	t.Run("FusenToUserUsingFusens", testFusenToOneSetOpUserUsingUser)
	t.Run("PreferenceToUserUsingPreferences", testPreferenceToOneSetOpUserUsingUser)
	t.Run("TagToUserUsingTags", testTagToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("FusenToCheckpoints", testFusenToManyAddOpCheckpoints)
	t.Run("UserToBoards", testUserToManyAddOpBoards)
	t.Run("UserToFusens", testUserToManyAddOpFusens)
	t.Run("UserToPreferences", testUserToManyAddOpPreferences)
	t.Run("UserToTags", testUserToManyAddOpTags)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}
