// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Boards      string
	Checkpoints string
	Fusens      string
	FusensTag   string
	Preferences string
	Tags        string
	Users       string
}{
	Boards:      "boards",
	Checkpoints: "checkpoints",
	Fusens:      "fusens",
	FusensTag:   "fusens_tag",
	Preferences: "preferences",
	Tags:        "tags",
	Users:       "users",
}
