// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFusens(t *testing.T) {
	t.Parallel()

	query := Fusens()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFusensDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFusensQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Fusens().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFusensSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FusenSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFusensExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FusenExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Fusen exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FusenExists to return true, but got false.")
	}
}

func testFusensFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	fusenFound, err := FindFusen(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if fusenFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFusensBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Fusens().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFusensOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Fusens().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFusensAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	fusenOne := &Fusen{}
	fusenTwo := &Fusen{}
	if err = randomize.Struct(seed, fusenOne, fusenDBTypes, false, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}
	if err = randomize.Struct(seed, fusenTwo, fusenDBTypes, false, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = fusenOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = fusenTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Fusens().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFusensCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	fusenOne := &Fusen{}
	fusenTwo := &Fusen{}
	if err = randomize.Struct(seed, fusenOne, fusenDBTypes, false, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}
	if err = randomize.Struct(seed, fusenTwo, fusenDBTypes, false, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = fusenOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = fusenTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func fusenBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func fusenAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func fusenAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func fusenBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func fusenAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func fusenBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func fusenAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func fusenBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func fusenAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Fusen) error {
	*o = Fusen{}
	return nil
}

func testFusensHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Fusen{}
	o := &Fusen{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, fusenDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Fusen object: %s", err)
	}

	AddFusenHook(boil.BeforeInsertHook, fusenBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	fusenBeforeInsertHooks = []FusenHook{}

	AddFusenHook(boil.AfterInsertHook, fusenAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	fusenAfterInsertHooks = []FusenHook{}

	AddFusenHook(boil.AfterSelectHook, fusenAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	fusenAfterSelectHooks = []FusenHook{}

	AddFusenHook(boil.BeforeUpdateHook, fusenBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	fusenBeforeUpdateHooks = []FusenHook{}

	AddFusenHook(boil.AfterUpdateHook, fusenAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	fusenAfterUpdateHooks = []FusenHook{}

	AddFusenHook(boil.BeforeDeleteHook, fusenBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	fusenBeforeDeleteHooks = []FusenHook{}

	AddFusenHook(boil.AfterDeleteHook, fusenAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	fusenAfterDeleteHooks = []FusenHook{}

	AddFusenHook(boil.BeforeUpsertHook, fusenBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	fusenBeforeUpsertHooks = []FusenHook{}

	AddFusenHook(boil.AfterUpsertHook, fusenAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	fusenAfterUpsertHooks = []FusenHook{}
}

func testFusensInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFusensInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(fusenColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFusenToManyCheckpoints(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Fusen
	var b, c Checkpoint

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, checkpointDBTypes, false, checkpointColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, checkpointDBTypes, false, checkpointColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.FusenID = a.ID
	c.FusenID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Checkpoints().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.FusenID == b.FusenID {
			bFound = true
		}
		if v.FusenID == c.FusenID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := FusenSlice{&a}
	if err = a.L.LoadCheckpoints(ctx, tx, false, (*[]*Fusen)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Checkpoints); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Checkpoints = nil
	if err = a.L.LoadCheckpoints(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Checkpoints); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testFusenToManyAddOpCheckpoints(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Fusen
	var b, c, d, e Checkpoint

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, fusenDBTypes, false, strmangle.SetComplement(fusenPrimaryKeyColumns, fusenColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Checkpoint{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, checkpointDBTypes, false, strmangle.SetComplement(checkpointPrimaryKeyColumns, checkpointColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Checkpoint{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCheckpoints(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.FusenID {
			t.Error("foreign key was wrong value", a.ID, first.FusenID)
		}
		if a.ID != second.FusenID {
			t.Error("foreign key was wrong value", a.ID, second.FusenID)
		}

		if first.R.Fusen != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Fusen != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Checkpoints[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Checkpoints[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Checkpoints().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testFusenToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Fusen
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, fusenDBTypes, false, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := FusenSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Fusen)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testFusenToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Fusen
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, fusenDBTypes, false, strmangle.SetComplement(fusenPrimaryKeyColumns, fusenColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Fusens[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testFusensReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFusensReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FusenSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFusensSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Fusens().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	fusenDBTypes = map[string]string{`ID`: `integer`, `UserID`: `integer`, `BoardID`: `character varying`, `Title`: `character varying`, `Memo`: `character varying`, `IsUrgent`: `boolean`, `IsImportant`: `boolean`, `Status`: `integer`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`, `SortNo`: `numeric`, `RemaindAt`: `character varying`}
	_            = bytes.MinRead
)

func testFusensUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(fusenPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(fusenAllColumns) == len(fusenPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFusensSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(fusenAllColumns) == len(fusenPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Fusen{}
	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, fusenDBTypes, true, fusenPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(fusenAllColumns, fusenPrimaryKeyColumns) {
		fields = fusenAllColumns
	} else {
		fields = strmangle.SetComplement(
			fusenAllColumns,
			fusenPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FusenSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFusensUpsert(t *testing.T) {
	t.Parallel()

	if len(fusenAllColumns) == len(fusenPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Fusen{}
	if err = randomize.Struct(seed, &o, fusenDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Fusen: %s", err)
	}

	count, err := Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, fusenDBTypes, false, fusenPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Fusen struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Fusen: %s", err)
	}

	count, err = Fusens().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
