// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFusensTags(t *testing.T) {
	t.Parallel()

	query := FusensTags()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFusensTagsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFusensTagsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := FusensTags().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFusensTagsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FusensTagSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFusensTagsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FusensTagExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if FusensTag exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FusensTagExists to return true, but got false.")
	}
}

func testFusensTagsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	fusensTagFound, err := FindFusensTag(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if fusensTagFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFusensTagsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = FusensTags().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFusensTagsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := FusensTags().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFusensTagsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	fusensTagOne := &FusensTag{}
	fusensTagTwo := &FusensTag{}
	if err = randomize.Struct(seed, fusensTagOne, fusensTagDBTypes, false, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}
	if err = randomize.Struct(seed, fusensTagTwo, fusensTagDBTypes, false, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = fusensTagOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = fusensTagTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := FusensTags().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFusensTagsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	fusensTagOne := &FusensTag{}
	fusensTagTwo := &FusensTag{}
	if err = randomize.Struct(seed, fusensTagOne, fusensTagDBTypes, false, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}
	if err = randomize.Struct(seed, fusensTagTwo, fusensTagDBTypes, false, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = fusensTagOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = fusensTagTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func fusensTagBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func fusensTagAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func fusensTagAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func fusensTagBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func fusensTagAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func fusensTagBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func fusensTagAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func fusensTagBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func fusensTagAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *FusensTag) error {
	*o = FusensTag{}
	return nil
}

func testFusensTagsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &FusensTag{}
	o := &FusensTag{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, fusensTagDBTypes, false); err != nil {
		t.Errorf("Unable to randomize FusensTag object: %s", err)
	}

	AddFusensTagHook(boil.BeforeInsertHook, fusensTagBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	fusensTagBeforeInsertHooks = []FusensTagHook{}

	AddFusensTagHook(boil.AfterInsertHook, fusensTagAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	fusensTagAfterInsertHooks = []FusensTagHook{}

	AddFusensTagHook(boil.AfterSelectHook, fusensTagAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	fusensTagAfterSelectHooks = []FusensTagHook{}

	AddFusensTagHook(boil.BeforeUpdateHook, fusensTagBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	fusensTagBeforeUpdateHooks = []FusensTagHook{}

	AddFusensTagHook(boil.AfterUpdateHook, fusensTagAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	fusensTagAfterUpdateHooks = []FusensTagHook{}

	AddFusensTagHook(boil.BeforeDeleteHook, fusensTagBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	fusensTagBeforeDeleteHooks = []FusensTagHook{}

	AddFusensTagHook(boil.AfterDeleteHook, fusensTagAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	fusensTagAfterDeleteHooks = []FusensTagHook{}

	AddFusensTagHook(boil.BeforeUpsertHook, fusensTagBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	fusensTagBeforeUpsertHooks = []FusensTagHook{}

	AddFusensTagHook(boil.AfterUpsertHook, fusensTagAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	fusensTagAfterUpsertHooks = []FusensTagHook{}
}

func testFusensTagsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFusensTagsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(fusensTagColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFusensTagsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFusensTagsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FusensTagSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFusensTagsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := FusensTags().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	fusensTagDBTypes = map[string]string{`ID`: `integer`, `FusenID`: `integer`, `TagID`: `integer`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_                = bytes.MinRead
)

func testFusensTagsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(fusensTagPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(fusensTagAllColumns) == len(fusensTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFusensTagsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(fusensTagAllColumns) == len(fusensTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &FusensTag{}
	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, fusensTagDBTypes, true, fusensTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(fusensTagAllColumns, fusensTagPrimaryKeyColumns) {
		fields = fusensTagAllColumns
	} else {
		fields = strmangle.SetComplement(
			fusensTagAllColumns,
			fusensTagPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FusensTagSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFusensTagsUpsert(t *testing.T) {
	t.Parallel()

	if len(fusensTagAllColumns) == len(fusensTagPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := FusensTag{}
	if err = randomize.Struct(seed, &o, fusensTagDBTypes, true); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert FusensTag: %s", err)
	}

	count, err := FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, fusensTagDBTypes, false, fusensTagPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize FusensTag struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert FusensTag: %s", err)
	}

	count, err = FusensTags().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
